In [3]:
import numpy as np
from glob import glob

In [2]:
fclouds = ['M3','M4','M8']

In [6]:
p,zeta1,zeta2,zeta3 = np.array([]),np.array([]),np.array([]),np.array([])
for icloud in fclouds:
    ifile = glob(('zeta_fitted_%s.out' % icloud))[0]
    print(ifile)
    tmpp,tmp1,tmp2,tmp3 = np.loadtxt(ifile,skiprows=1,usecols=(0,1,2,3),unpack=True)
    p = np.append(p,tmpp)
    zeta1 = np.append(zeta1,tmp1)
    zeta2 = np.append(zeta2,tmp2)
    zeta3 = np.append(zeta3,tmp3)

zeta_fitted_M3.out
zeta_fitted_M4.out
zeta_fitted_M8.out


In [17]:
# p = 1
zmin = 0.241
ezmin = 0
zmax = 0.5
ezmax = 0.3
p1 = np.sort(np.unique(p[np.where((zeta1>=zmin) & (zeta1<=zmax))]))
ep1 = np.sort(np.unique(p[np.where((zeta1>=zmin-ezmin) & (zeta1<=zmax+ezmax))]))
print(p1,ep1)
print(np.min(p1),np.max(p1))
print(np.min(ep1),np.max(ep1))

(array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9]), array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9]))
(1.0, 3.8999999999999999)
(0.0, 3.8999999999999999)


In [18]:
# p = 2
zmin = 0.76
ezmin = 0
zmax = 0.86
ezmax = 0.3
p2 = np.sort(np.unique(p[np.where((zeta2>=zmin) & (zeta2<=zmax))]))
ep2 = np.sort(np.unique(p[np.where((zeta2>=zmin-ezmin) & (zeta2<=zmax+ezmax))]))
print(p2,ep2)
print(np.min(p2),np.max(p2))
print(np.min(ep2),np.max(ep2))

(array([ 1.1,  1.2,  1.5,  1.8,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,
        2.7,  2.8,  2.9,  3. ,  3.1]), array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1]))
(1.1000000000000001, 3.1000000000000001)
(0.0, 3.1000000000000001)


In [19]:
# p = 3
zmin = 1.1
ezmin = 0
zmax = 1.18
ezmax = 0
p3 = np.sort(np.unique(p[np.where((zeta3>=zmin) & (zeta3<=zmax))]))
ep3 = np.sort(np.unique(p[np.where((zeta3>=zmin-ezmin) & (zeta3<=zmax+ezmax))]))
print(p3,ep3)
print(np.min(p3),np.max(p3))
print(np.min(ep3),np.max(ep3))

(array([ 1.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  3. ]), array([ 1.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  3. ]))
(1.1000000000000001, 3.0)
(1.1000000000000001, 3.0)
